server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?serverTimezone=Asia/Seoul&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456